//import mascotCardsCollection from '../src/data/cardsCollection'
import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from "react"

//import MascotCards from './MascotCard'

import styles from '../styles/Home.module.css'

export default function Home() {
  const [showFaces, setShowFaces] = useState([]);
  const [matchedCards, setMatchedCards] = useState([]);


  const checkMatch = (clickedCard1, clickedCard2, event) => {
    const card1 = document.getElementById(clickedCard1).dataset.cardupid;
    const card2 = document.getElementById(clickedCard2).dataset.cardupid;
    console.log(card1 == card2, event)
    card1 === card2 ? setMatchedCards([...matchedCards, clickedCard1, clickedCard2]) : setShowFaces([]) ;

    //const cardID = event.target.dataset.cardID;
    // if (
    //   clickedCard1 !== clickedCard2
    // ) {
    //   setMatchedCards([...matchedCards, clickedCard1, clickedCard2]);
    // }
  };
  
  function handleClick(event, elClass, index){

    const cardID = event.target.dataset.cardupid;
    console.log(`You clicked ${elClass}, ${event.target.dataset.cardupid}.`);
    //showFace(elClass)
    //setShowFaces([cardID]);
    //console.log(showFaces);
    // Manage clicks 
    if (!matchedCards.includes(index)) {
      switch (showFaces.length) {
        case 0:
          setShowFaces([index]);
          break;
        case 1:
          if (showFaces[0] !== index) {  //when user clicks on the same card
            setShowFaces(showFaces.concat(index));
            //checkUniqueCardsEventHandler(showFaces[0], index);
            //checkMatch(showFaces[0], index, event);
            setTimeout(() => { checkMatch(showFaces[0], index, event); }, 2000);
          }
          break;
        default:
          setShowFaces([index]);
      }
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Sidearm Sports Senior FE Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} role="main">
        <Image src="/hero-fans.jpg" alt="" layout="fill" id="" className={styles.hero} />
        <header role="banner">
          <h1 className={styles.title}>
            Welcome to NY College Sports <br />Mascots Memory Game
          </h1>
        </header>

        <ul className={styles.grid} data-card-table>
          {/* {
            mascotCardsCollection.forEach(card => {
              console.log(card)
              return <li>{card}</li>;
            })
          } */}
           <li><div data-cardupid="1" id="1" className={`${styles.card} ${showFaces?.includes(1) ? styles.cardshow : ""} ${matchedCards?.includes(1) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 1)}><Image src="/img-ny-bmcc.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="2" id="2" className={`${styles.card} ${showFaces?.includes(2) ? styles.cardshow : ""} ${matchedCards?.includes(2) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 2)}><Image src="/img-ny-binghamton-bearcats.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="3" id="3" className={`${styles.card} ${showFaces?.includes(3) ? styles.cardshow : ""} ${matchedCards?.includes(3) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 3)}><Image src="/img-ny-bronx-community.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="4" id="4" className={`${styles.card} ${showFaces?.includes(4) ? styles.cardshow : ""} ${matchedCards?.includes(4) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 4)}><Image src="/img-ny-c1.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="5" id="5" className={`${styles.card} ${showFaces?.includes(5) ? styles.cardshow : ""} ${matchedCards?.includes(5) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 5)}><Image src="/img-ny-canisius.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="6" id="6" className={`${styles.card} ${showFaces?.includes(6) ? styles.cardshow : ""} ${matchedCards?.includes(6) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 6)}><Image src="/img-ny-clarkson.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="7" id="7" className={`${styles.card} ${showFaces?.includes(7) ? styles.cardshow : ""} ${matchedCards?.includes(7) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 7)}><Image src="/img-ny-colgate.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="8" id="8" className={`${styles.card} ${showFaces?.includes(8) ? styles.cardshow : ""} ${matchedCards?.includes(8) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 8)}><Image src="/img-ny-cortland.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="9" id="9" className={`${styles.card} ${showFaces?.includes(9) ? styles.cardshow : ""} ${matchedCards?.includes(9) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 9)}><Image src="/img-ny-rit.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="10" id="10" className={`${styles.card} ${showFaces?.includes(10) ? styles.cardshow : ""} ${matchedCards?.includes(10) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 10)}><Image src="/img-ny-rutgers.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="11" id="11" className={`${styles.card} ${showFaces?.includes(11) ? styles.cardshow : ""} ${matchedCards?.includes(11) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 11)}><Image src="/img-ny-st-johns.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="12" id="12" className={`${styles.card} ${showFaces?.includes(12) ? styles.cardshow : ""} ${matchedCards?.includes(12) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 12)}><Image src="/img-ny-syracuse.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="1" id="13" className={`${styles.card} ${showFaces?.includes(13) ? styles.cardshow : ""} ${matchedCards?.includes(13) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 13)}><Image src="/img-ny-bmcc.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="2" id="14" className={`${styles.card} ${showFaces?.includes(14) ? styles.cardshow : ""} ${matchedCards?.includes(14) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 14)}><Image src="/img-ny-binghamton-bearcats.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="3" id="15" className={`${styles.card} ${showFaces?.includes(15) ? styles.cardshow : ""} ${matchedCards?.includes(15) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 15)}><Image src="/img-ny-bronx-community.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="4" id="16" className={`${styles.card} ${showFaces?.includes(16) ? styles.cardshow : ""} ${matchedCards?.includes(16) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 16)}><Image src="/img-ny-c1.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="5" id="17" className={`${styles.card} ${showFaces?.includes(17) ? styles.cardshow : ""} ${matchedCards?.includes(17) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 17)}><Image src="/img-ny-canisius.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="6" id="18" className={`${styles.card} ${showFaces?.includes(18) ? styles.cardshow : ""} ${matchedCards?.includes(18) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 18)}><Image src="/img-ny-clarkson.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="7" id="19" className={`${styles.card} ${showFaces?.includes(19) ? styles.cardshow : ""} ${matchedCards?.includes(19) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 19)}><Image src="/img-ny-colgate.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="8" id="20" className={`${styles.card} ${showFaces?.includes(20) ? styles.cardshow : ""} ${matchedCards?.includes(20) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 20)}><Image src="/img-ny-cortland.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="9" id="21" className={`${styles.card} ${showFaces?.includes(21) ? styles.cardshow : ""} ${matchedCards?.includes(21) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 21)}><Image src="/img-ny-rit.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="10" id="22" className={`${styles.card} ${showFaces?.includes(22) ? styles.cardshow : ""} ${matchedCards?.includes(22) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 22)}><Image src="/img-ny-rutgers.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="11" id="23" className={`${styles.card} ${showFaces?.includes(23) ? styles.cardshow : ""} ${matchedCards?.includes(23) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 23)}><Image src="/img-ny-st-johns.png" width={45} height={45} /></div></li>
           <li><div data-cardupid="12" id="24" className={`${styles.card} ${showFaces?.includes(24) ? styles.cardshow : ""} ${matchedCards?.includes(24) ? styles.cardmatched : ""}`} onClick={()=>handleClick(event, styles.card, 24)}><Image src="/img-ny-syracuse.png" width={45} height={45} /></div></li>

        </ul>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
