import mascotCardsCollection from '../src/data/cardsCollection'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


console.log(mascotCardsCollection)
export default function Home() {

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Sidearm Sports Senior FE Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} role="main">
        <Image src="/hero-fans.jpg" alt="" layout="fill" className={styles.hero} />
        <header role="banner">
          <h1 className={styles.title}>
            Welcome to NY College Sports <br />Mascots Memory Game
          </h1>
        </header>

        <ul className={styles.grid}>
        
          {/* {
            console.log(cardsCollection)}
          {
            cardsCollection.forEach(card => {
              return <li>test</li>;
            })
          }
           */}
           <li className={styles.card}><img src="/img-ny-bmcc.png" alt="" /></li>
           <li className={styles.card}><img /></li>
           <li className={styles.card}><img /></li>
           <li className={styles.card}><img /></li>
           <li className={styles.card}><img /></li>
           <li className={styles.card}><img /></li>
           <li className={styles.card}><img /></li>
           <li className={styles.card}><img /></li>

        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
